# Récupération du texte intégral des articles TASS sélectionnés

Ce notebook constitue l’étape qui suit l’entraînement du classifieur thématique. À partir du corpus TASS déjà filtré par le modèle, il prépare une liste propre d’articles pertinents, puis récupère automatiquement le texte intégral de chaque article directement depuis les pages TASS.

L’objectif est donc de passer d’un corpus minimal — composé principalement des titres, dates et liens — à un corpus enrichi contenant le contenu textuel complet des articles. Ce corpus pourra ensuite être utilisé pour l’analyse qualitative, l’annotation narrative, le topic modeling ou d’autres traitements textuels.

## 1. Imports

In [1]:
import json
import pandas as pd

## 2. Chargement du corpus retenu par le classifieur

Cette section charge le fichier `tass_pred_score_gt_0575.json`, qui contient les articles sélectionnés comme pertinents par le classifieur thématique. Pour chaque article, on conserve les champs essentiels : le titre, la date de publication et l’URL.

Le résultat est transformé en `DataFrame` afin de faciliter les vérifications, les fusions éventuelles et la sauvegarde dans un format propre.

In [ ]:

input_path = "tass_pred_score_gt_0575.json"

with open(input_path, "r", encoding="utf-8") as f:
    data = json.load(f)

rows = []
for obj in data:
    title = obj.get("title")
    published_dt = obj.get("published_dt")
    url = obj.get("url")

    if title and published_dt:
        rows.append({
            "title": title,
            "published_dt": published_dt,
            "url": url
        })

df = pd.DataFrame(rows)

df

,title,published_dt,url
0,"Волонтеры развернули штаб ""Мы вместе"" для помо...",2022-02-18T22:21:32,https://tass.ru/obschestvo/13763103
1,"Волонтер рассказал о помощи жителям ДНР, котор...",2022-02-18T22:09:51,https://tass.ru/obschestvo/13762975
2,Роспотребнадзор уделит особое внимание организ...,2022-02-18T20:56:09,https://tass.ru/obschestvo/13762457
3,Из Луганска в Россию отправился первый автобус...,2022-02-18T20:53:55,https://tass.ru/obschestvo/13762389
4,Источник: для эвакуированных из ДНР и ЛНР разв...,2022-02-18T20:53:50,https://tass.ru/obschestvo/13762407
...,...,...,...
1795,В лагерях Подмосковья отдохнут более 450 детей...,2025-11-17T10:43:43,https://tass.ru/obschestvo/25645485
1796,Число эвакуированных жителей Двуречной в Харьк...,2025-11-24T14:58:50,https://tass.ru/obschestvo/25714785
1797,В Селидове ДНР развернули ПВР для беженцев из ...,2025-11-30T12:08:01,https://tass.ru/obschestvo/25773921
1798,В проекте РКК прошли обучение свыше 500 пересе...,2025-12-05T11:25:12,https://tass.ru/obschestvo/25828613
1799,В Липецкой области сообщили о начале возвращен...,2025-12-08T17:56:39,https://tass.ru/obschestvo/25849183

## 3. Chargement d’un corpus complémentaire

Cette cellule charge un second fichier, `tass_data.csv`, qui contient des articles collectés ou conservés dans un autre format. Cette étape permet de comparer les deux sources et, si nécessaire, d’ajouter au corpus principal des articles qui n’auraient pas été présents dans le fichier issu du classifieur.

In [2]:
csv_path_2 = "tass_data.csv"
df2 = pd.read_csv(csv_path_2)
df2

,Unnamed: 0,Titre de l'article,Titre fr,Date,Lien
0,0,Власти ДНР организовали массовый централизован...,Les autorités de la RPD ont organisé un départ...,2022-02-18 13:10:00,https://tass.ru/mezhdunarodnaya-panorama/13756493
1,1,"В Думе заявили, что Ростовская область справит...",La Douma a déclaré que la région de Rostov se ...,2022-02-18 13:46:00,https://tass.ru/politika/13757209
2,2,Пескову неизвестно об эвакуации жителей Донбас...,Peskov ignore l'évacuation des habitants du Do...,2022-02-18 14:10:00,https://tass.ru/politika/13757849
3,3,Власти Крыма заявили о готовности принять жите...,Les autorités de Crimée ont annoncé qu'elles é...,2022-02-18 14:18:00,https://tass.ru/politika/13757407
4,4,ДНР и ЛНР объявили об эвакуации мирных жителей...,La RPD et la LPR ont annoncé l'évacuation des ...,2022-02-18 15:19:00,https://tass.ru/mezhdunarodnaya-panorama/13758699
...,...,...,...,...,...
291,291,"Более 5,1 млн беженцев прибыли в Россию с терр...","Plus de 5,1 millions de réfugiés sont arrivés ...",2023-01-09 07:56:00,https://tass.ru/obschestvo/16757749
292,292,"С февраля 2022 года в Россию прибыли более 5,2...","Depuis février 2022, plus de 5,2 millions de r...",2023-01-30 07:25:00,https://tass.ru/obschestvo/16914809
293,293,Российское гражданство с 2019 года получили бо...,"Plus de 1,4 million d'Ukrainiens ont obtenu la...",2023-02-02 07:56:00,https://tass.ru/obschestvo/16943909
294,294,За год с Украины и из Донбасса на территорию Р...,"Au cours de l'année, 5,3 millions de réfugiés ...",2023-02-20 07:06:00,https://tass.ru/obschestvo/17091725
295,295,В Россию с территории Донбасса и Украины прибы...,"5,5 millions de réfugiés sont arrivés en Russi...",2023-03-28 06:40:00,https://tass.ru/obschestvo/17383893

## 4. Harmonisation des formats et ajout des articles manquants

Le second corpus n’a pas exactement les mêmes noms de colonnes que le corpus principal. Cette cellule le remet donc dans une structure commune avec trois champs : `title`, `published_dt` et `url`.

Les URL sont ensuite normalisées afin de comparer correctement les deux corpus, même en présence de différences mineures de casse, d’espaces ou de barres finales. Seules les lignes dont l’URL n’est pas déjà présente dans le corpus principal sont ajoutées.

In [12]:
# 2) приводим второй df к схеме первого
df2_std = pd.DataFrame({
    "title": df2["Titre de l'article"].fillna(df2.get("Titre fr")),  # если нет RU-заголовка, подставим FR
    "published_dt": pd.to_datetime(df2["Date"], errors="coerce"),    # дата -> datetime
    "url": df2["Lien"],
})

# если в df published_dt строкой — можно обратно в ISO (не обязательно)
# df2_std["published_dt"] = df2_std["published_dt"].dt.strftime("%Y-%m-%dT%H:%M:%S")

# 3) добавляем только те строки, которых нет в df по url
def norm_url(s):
    return (
        s.astype(str).str.strip().str.lower()
        .str.replace(r"\s+", "", regex=True)
        .str.replace(r"/+$", "", regex=True)
        .replace({"nan": pd.NA, "none": pd.NA, "": pd.NA})
    )

df["_url_norm"] = norm_url(df["url"])
df2_std["_url_norm"] = norm_url(df2_std["url"])

to_add = df2_std[df2_std["_url_norm"].notna() & ~df2_std["_url_norm"].isin(df["_url_norm"])].copy()
print("Новых строк:", len(to_add))

df = pd.concat([df.drop(columns=["_url_norm"], errors="ignore"),
                to_add.drop(columns=["_url_norm"], errors="ignore")],
               ignore_index=True)

df.head()

Новых строк: 70

,title,published_dt,url
0,"Волонтеры развернули штаб ""Мы вместе"" для помо...",2022-02-18T22:21:32,https://tass.ru/obschestvo/13763103
1,"Волонтер рассказал о помощи жителям ДНР, котор...",2022-02-18T22:09:51,https://tass.ru/obschestvo/13762975
2,Роспотребнадзор уделит особое внимание организ...,2022-02-18T20:56:09,https://tass.ru/obschestvo/13762457
3,Из Луганска в Россию отправился первый автобус...,2022-02-18T20:53:55,https://tass.ru/obschestvo/13762389
4,Источник: для эвакуированных из ДНР и ЛНР разв...,2022-02-18T20:53:50,https://tass.ru/obschestvo/13762407

## 5. Contrôle des articles non appariés

Cette cellule sert de vérification complémentaire après l’harmonisation du second corpus. Elle identifie les articles du fichier CSV qui ne correspondent pas aux URL déjà présentes dans le corpus principal et affiche leurs dates de publication.

Ce contrôle permet de comprendre quels articles ont été ajoutés, et de vérifier que les différences entre les deux sources ne proviennent pas seulement de variations de format dans les URL.

In [13]:
def norm_url(s):
    return (
        s.astype(str).str.strip().str.lower()
        .str.replace(r"\s+", "", regex=True)
        .str.replace(r"/+$", "", regex=True)
        .replace({"nan": pd.NA, "none": pd.NA, "": pd.NA})
    )

# считаем нормализованные url отдельно, не меняя df
df_url_norm = norm_url(df["url"])
df2_url_norm = norm_url(df2_std["url"])

# строки из df2_std, которые НЕ совпали бы с df
not_matched = df2_std[
    df2_url_norm.notna() &
    ~df2_url_norm.isin(df_url_norm)
].copy()

# все значения published_dt
all_dates_not_matched = not_matched["published_dt"].copy()

print("Строк, которые НЕ совпали бы:", len(not_matched))
dates_list = not_matched["published_dt"].dropna().tolist()
print(dates_list)

Строк, которые НЕ совпали бы: 70
[Timestamp('2022-02-18 13:10:00'), Timestamp('2022-02-18 14:10:00'), Timestamp('2022-02-18 15:19:00'), Timestamp('2022-02-18 16:48:00'), Timestamp('2022-02-18 17:45:00'), Timestamp('2022-02-18 17:47:00'), Timestamp('2022-02-18 18:43:00'), Timestamp('2022-02-18 18:48:00'), Timestamp('2022-02-18 20:06:00'), Timestamp('2022-02-18 20:23:00'), Timestamp('2022-02-18 21:58:00'), Timestamp('2022-02-18 23:17:00'), Timestamp('2022-02-18 23:51:00'), Timestamp('2022-02-19 00:10:00'), Timestamp('2022-02-19 00:54:00'), Timestamp('2022-02-19 00:55:00'), Timestamp('2022-02-19 05:14:00'), Timestamp('2022-02-19 06:07:00'), Timestamp('2022-02-19 07:10:00'), Timestamp('2022-02-19 08:10:00'), Timestamp('2022-02-19 08:38:00'), Timestamp('2022-02-19 09:11:00'), Timestamp('2022-02-19 09:19:00'), Timestamp('2022-02-19 09:58:00'), Timestamp('2022-02-19 11:02:00'), Timestamp('2022-02-19 11:50:00'), Timestamp('2022-02-19 16:47:00'), Timestamp('2022-02-19 17:18:00'), Timestamp('2022-02-19 17:59:00'), Timestamp('2022-02-19 18:33:00'), Timestamp('2022-02-19 18:49:00'), Timestamp('2022-02-19 19:04:00'), Timestamp('2022-02-20 06:36:00'), Timestamp('2022-02-20 06:50:00'), Timestamp('2022-02-20 07:05:00'), Timestamp('2022-02-20 07:13:00'), Timestamp('2022-02-20 08:11:00'), Timestamp('2022-02-20 11:59:00'), Timestamp('2022-02-20 12:22:00'), Timestamp('2022-02-20 17:57:00'), Timestamp('2022-02-21 10:01:00'), Timestamp('2022-02-21 10:12:00'), Timestamp('2022-02-21 10:20:00'), Timestamp('2022-02-21 11:18:00'), Timestamp('2022-02-21 11:27:00'), Timestamp('2022-02-21 11:47:00'), Timestamp('2022-02-21 13:06:00'), Timestamp('2022-02-21 13:51:00'), Timestamp('2022-02-21 14:57:00'), Timestamp('2022-02-21 15:11:00'), Timestamp('2022-02-22 09:56:00'), Timestamp('2022-02-22 10:27:00'), Timestamp('2022-02-22 10:46:00'), Timestamp('2022-02-22 12:15:00'), Timestamp('2022-02-22 13:04:00'), Timestamp('2022-02-22 13:14:00'), Timestamp('2022-02-22 15:28:00'), Timestamp('2022-02-22 17:08:00'), Timestamp('2022-02-22 17:54:00'), Timestamp('2022-02-22 18:47:00'), Timestamp('2022-02-28 11:06:00'), Timestamp('2022-03-07 14:22:00'), Timestamp('2022-03-23 18:03:00'), Timestamp('2022-03-31 18:33:00'), Timestamp('2022-04-08 14:35:00'), Timestamp('2022-04-13 05:15:00'), Timestamp('2022-06-24 11:41:00'), Timestamp('2022-07-21 13:51:00'), Timestamp('2022-10-05 19:26:00'), Timestamp('2023-02-02 07:56:00')]

## 6. Sauvegarde du corpus minimal nettoyé

Après fusion et déduplication, le corpus minimal est sauvegardé dans le dossier `tass_clean`. Le fichier produit, `tass_clean.json`, contient une liste d’articles avec leurs métadonnées principales.

Cette sauvegarde crée un point de départ stable pour l’étape suivante : le scraping du texte intégral.

In [15]:
# 1) создаём папку
out_dir = "tass_clean"
os.makedirs(out_dir, exist_ok=True)

# 2) делаем копию df и приводим даты к строке (иначе json может сломаться)
df_to_save = df.copy()

if "published_dt" in df_to_save.columns:
    df_to_save["published_dt"] = df_to_save["published_dt"].astype(str)

# 3) путь к файлу
out_path = os.path.join(out_dir, "tass_clean.json")

# 4) сохраняем в JSON
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(df_to_save.to_dict(orient="records"), f, ensure_ascii=False, indent=2)

print("Saved to:", out_path)
print("Rows saved:", len(df_to_save))

Saved to: tass_clean/tass_clean.json
Rows saved: 1870

## 7. Préparation du scraping du texte intégral

Cette section importe les bibliothèques nécessaires au scraping des pages TASS. `Playwright` permet d’ouvrir les pages dans un navigateur automatisé, tandis que `asyncio`, `random` et `tqdm` servent à gérer l’exécution asynchrone, les pauses entre les requêtes et le suivi de la progression.

In [ ]:
import json
import os
import re
import random
import asyncio
from tqdm import tqdm
from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeoutError

## 8. Fonctions d’extraction et de sauvegarde

Les fonctions suivantes organisent tout le processus d’enrichissement du corpus. Elles permettent de charger le fichier JSON d’entrée, de nettoyer les textes, d’extraire le corps des articles à partir de sélecteurs HTML, de récupérer quelques hashtags ou mots-clés, puis de sauvegarder régulièrement le résultat.

Le scraping est conçu pour être relativement robuste : il ignore les articles déjà enrichis, utilise plusieurs tentatives en cas d’échec, introduit des pauses aléatoires pour éviter des requêtes trop agressives et effectue des sauvegardes atomiques afin de limiter le risque de corruption du fichier.

In [ ]:

def nettoyer_texte(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "")).strip()

def charger_articles(input_path: str):
    print(f"Chargement du fichier JSON : {input_path}")
    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if isinstance(data, dict):
        print("Format détecté : dictionnaire avec clés numériques (0, 1, 2...)")
        keys = sorted(data.keys(), key=lambda x: int(x) if str(x).isdigit() else str(x))
        return data, keys, "dict"
    elif isinstance(data, list):
        print("Format détecté : liste d'articles")
        return data, list(range(len(data))), "list"
    else:
        raise ValueError("Format JSON inattendu (ni dict ni liste).")

def out_path_from_input(input_path: str, out_filename: str = "tass_clean_with_text.json") -> str:
    os.makedirs("tass_clean", exist_ok=True)
    return os.path.join("tass_clean", out_filename)

def save_json_atomic(data, path: str):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    os.replace(tmp, path)

async def pause_humaine(i: int):
    await asyncio.sleep(random.uniform(2.5, 6.5))
    if i > 0 and i % 25 == 0:
        await asyncio.sleep(random.uniform(15, 45))
    if i > 0 and i % 120 == 0:
        await asyncio.sleep(random.uniform(90, 180))

# ------------- EXTRACTION TEXTE (comme ton test) -------------
async def extraire_texte_tass_playwright(page) -> str:
    # 1) Sélecteur sémantique
    body = page.locator('[itemprop="articleBody"]')
    if await body.count() > 0:
        ps = await body.locator("p").all_inner_texts()
        ps = [nettoyer_texte(p) for p in ps if nettoyer_texte(p)]
        if ps:
            return "\n".join(ps).strip()

    # 2) Selecteurs alternatifs
    candidats = ["article", "div.article__text", "div.news-content", "div.content", "div.text"]
    meilleur = ""
    for sel in candidats:
        loc = page.locator(sel)
        if await loc.count() == 0:
            continue
        ps = await loc.first.locator("p").all_inner_texts()
        ps = [nettoyer_texte(p) for p in ps if nettoyer_texte(p)]
        txt = "\n".join(ps).strip()
        if len(txt) > len(meilleur):
            meilleur = txt

    # IMPORTANT: on retourne seulement si ça ressemble à un vrai texte d'article
    if len(meilleur) >= 200:
        return meilleur

    # 3) Dernier recours: on évite inner_text("body") (trop de bruit sur TASS)
    return ""

# ------------- HASHTAGS (léger, sans meta qui timeout) -------------
async def extraire_hashtags_simple(page) -> list[str]:
    """
    TASS n'a pas toujours de meta keywords. On récupère des tags via liens internes,
    en restant conservateur.
    """
    tags = set()

    # On cherche d'abord dans 'article' si présent
    containers = [page.locator("article"), page.locator("main"), page.locator("body")]
    chosen = None
    for c in containers:
        try:
            if await c.count() > 0:
                chosen = c.first
                break
        except Exception:
            pass
    if not chosen:
        return []

    # Liens qui ressemblent à des tags/thèmes/personnes/régions
    a = chosen.locator("a")
    try:
        n = await a.count()
        for i in range(min(n, 400)):  # limite pour rester léger
            href = await a.nth(i).get_attribute("href")
            txt = nettoyer_texte(await a.nth(i).inner_text())
            if not href or not txt or len(txt) > 45:
                continue
            href = href.strip()

            # heuristique conservatrice
            if any(x in href for x in ["/tag/", "/tema/", "/person/", "/region/", "/rossiya", "/ukraina", "/dnr", "/lnr"]):
                tags.add(txt)
    except Exception:
        pass

    # nettoyage minimal
    bad = {"ТАСС", "TASS", "Главная", "Общество", "Политика"}
    tags = [t for t in tags if t not in bad]
    tags = sorted(set(tags))
    return tags

# ------------- MAIN -------------
async def enrichir_tass_all(
    input_path: str = "tass_clean/tass_clean.json",
    output_filename: str = "tass_clean_with_text.json",
    headless: bool = True,
    save_every: int = 20,
    max_retries: int = 3,
    min_len: int = 200
):
    data, keys, kind = charger_articles(input_path)
    out_path = out_path_from_input(input_path, output_filename)

    total = len(keys)
    print(f"Nombre total d'articles : {total}")
    print(f"Fichier de sortie      : {out_path}")

    async with async_playwright() as p:
        print("Lancement du navigateur Chromium...")
        browser = await p.chromium.launch(headless=headless)
        context = await browser.new_context(
            viewport={"width": 1280, "height": 720},
            user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                       "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            locale="fr-FR",
        )
        page = await context.new_page()

        ok = 0
        skipped = 0
        failed = 0

        pbar = tqdm(total=total, desc="Articles", unit="article")

        try:
            for idx, k in enumerate(keys):
                item = data[k] if kind == "dict" else data[k]
                url = item.get("url")

                if not url:
                    skipped += 1
                    pbar.update(1)
                    continue

                # skip si déjà texte valide
                existing = item.get("text")
                if isinstance(existing, str) and len(existing.strip()) >= min_len:
                    skipped += 1
                    pbar.update(1)
                    continue

                await pause_humaine(ok + failed)

                texte = ""
                hashtags = []

                last_reason = ""

                for attempt in range(1, max_retries + 1):
                    try:
                        await page.goto(url, wait_until="domcontentloaded", timeout=60000)
                        await page.wait_for_timeout(1500)

                        # точно как в твоем тесте
                        texte = await extraire_texte_tass_playwright(page)

                        # hashtags — отдельно (не обязательно)
                        hashtags = await extraire_hashtags_simple(page)

                        if texte and len(texte.strip()) >= min_len:
                            break
                        else:
                            last_reason = "Texte vide/trop court"
                            await asyncio.sleep(random.uniform(6, 12))

                    except PlaywrightTimeoutError:
                        last_reason = "Délai dépassé"
                        await asyncio.sleep(random.uniform(8, 15))
                    except Exception as e:
                        last_reason = f"Erreur: {e}"
                        await asyncio.sleep(random.uniform(8, 15))

                if texte and len(texte.strip()) >= min_len:
                    item["text"] = texte
                    item["hashtags"] = hashtags
                    item.pop("_scrape_status", None)
                    ok += 1
                else:
                    item["text"] = ""  # лучше пусто, чем мусор из body
                    item["hashtags"] = hashtags if hashtags else []
                    item["_scrape_status"] = f"ECHEC: {last_reason}"
                    failed += 1

                # autosave
                if (ok + failed) % save_every == 0:
                    save_json_atomic(data, out_path)
                    print(f"\nSauvegarde intermédiaire : ok={ok}, échecs={failed}, sautés={skipped} -> {out_path}")

                pbar.update(1)

            # save final
            save_json_atomic(data, out_path)

        finally:
            pbar.close()
            await context.close()
            await browser.close()

    print("=== TERMINÉ ===")
    print(f"Réussites : {ok}")
    print(f"Échecs    : {failed}")
    print(f"Sautés    : {skipped}")
    print(f"Fichier   : {out_path}")

# запуск:
# await enrichir_tass_all("tass_clean/tass_clean.json", "tass_clean_with_text.json", headless=True)

## 9. Lancement de l’enrichissement du corpus

Cette cellule lance le scraping du texte intégral pour tous les articles présents dans `tass_clean.json`. Pour chaque URL, le script ouvre la page TASS, tente d’extraire le texte de l’article et ajoute deux champs au corpus : `text` et `hashtags`.

Le fichier enrichi est sauvegardé progressivement sous le nom `tass_clean_with_text.json`, ce qui permet de reprendre ou de contrôler le travail même si l’exécution est interrompue.

In [51]:
await enrichir_tass_all(
    input_path="tass_clean/tass_clean.json",
    output_filename="tass_clean_with_text.json",
    headless=True,
    save_every=10,
    max_retries=3
)

Chargement du fichier JSON : tass_clean/tass_clean.json
Format détecté : liste d'articles
Nombre total d'articles : 1870
Fichier de sortie      : tass_clean/tass_clean_with_text.json
Lancement du navigateur Chromium...

Articles:   1%|▏                                     | 11/1870 [01:08<3:33:15,  6.88s/article]

Sauvegarde intermédiaire : ok=10, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   1%|▍                                     | 21/1870 [02:16<3:57:18,  7.70s/article]

Sauvegarde intermédiaire : ok=20, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   2%|▋                                     | 31/1870 [03:50<4:16:35,  8.37s/article]

Sauvegarde intermédiaire : ok=30, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   2%|▊                                     | 41/1870 [04:57<3:17:15,  6.47s/article]

Sauvegarde intermédiaire : ok=40, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   3%|█                                     | 51/1870 [06:03<3:21:59,  6.66s/article]

Sauvegarde intermédiaire : ok=50, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   3%|█▏                                    | 61/1870 [07:53<3:58:17,  7.90s/article]

Sauvegarde intermédiaire : ok=60, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   4%|█▍                                    | 71/1870 [09:01<3:47:31,  7.59s/article]

Sauvegarde intermédiaire : ok=70, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   4%|█▋                                    | 81/1870 [10:23<3:55:38,  7.90s/article]

Sauvegarde intermédiaire : ok=80, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   5%|█▊                                    | 91/1870 [11:25<3:08:31,  6.36s/article]

Sauvegarde intermédiaire : ok=90, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   5%|█▉                                   | 101/1870 [12:34<3:24:27,  6.93s/article]

Sauvegarde intermédiaire : ok=100, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   6%|██▏                                  | 111/1870 [13:56<3:22:27,  6.91s/article]

Sauvegarde intermédiaire : ok=110, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   6%|██▍                                  | 121/1870 [15:01<3:06:52,  6.41s/article]

Sauvegarde intermédiaire : ok=120, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   7%|██▌                                  | 131/1870 [18:51<5:19:21, 11.02s/article]

Sauvegarde intermédiaire : ok=130, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   8%|██▊                                  | 141/1870 [20:02<3:20:10,  6.95s/article]

Sauvegarde intermédiaire : ok=140, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   8%|██▉                                  | 151/1870 [21:09<2:52:31,  6.02s/article]

Sauvegarde intermédiaire : ok=150, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   9%|███▏                                 | 161/1870 [22:28<3:08:26,  6.62s/article]

Sauvegarde intermédiaire : ok=160, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:   9%|███▍                                 | 171/1870 [23:40<3:30:52,  7.45s/article]

Sauvegarde intermédiaire : ok=170, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  10%|███▌                                 | 181/1870 [25:20<4:12:44,  8.98s/article]

Sauvegarde intermédiaire : ok=180, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  10%|███▊                                 | 191/1870 [26:27<2:53:24,  6.20s/article]

Sauvegarde intermédiaire : ok=190, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  11%|███▉                                 | 201/1870 [27:34<3:21:15,  7.24s/article]

Sauvegarde intermédiaire : ok=200, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  11%|████▏                                | 211/1870 [29:16<4:09:25,  9.02s/article]

Sauvegarde intermédiaire : ok=210, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  12%|████▎                                | 221/1870 [30:25<3:17:08,  7.17s/article]

Sauvegarde intermédiaire : ok=220, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  12%|████▌                                | 231/1870 [32:09<4:10:10,  9.16s/article]

Sauvegarde intermédiaire : ok=230, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  13%|████▊                                | 241/1870 [33:12<2:46:27,  6.13s/article]

Sauvegarde intermédiaire : ok=240, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  13%|████▉                                | 251/1870 [36:53<3:52:56,  8.63s/article]

Sauvegarde intermédiaire : ok=250, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  14%|█████▏                               | 261/1870 [38:37<2:46:09,  6.20s/article]

Sauvegarde intermédiaire : ok=260, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  14%|█████▎                               | 271/1870 [39:42<3:02:32,  6.85s/article]

Sauvegarde intermédiaire : ok=270, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  15%|█████▌                               | 281/1870 [41:21<3:37:43,  8.22s/article]

Sauvegarde intermédiaire : ok=280, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  16%|█████▊                               | 291/1870 [42:26<2:54:29,  6.63s/article]

Sauvegarde intermédiaire : ok=290, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  16%|█████▉                               | 301/1870 [43:30<2:56:47,  6.76s/article]

Sauvegarde intermédiaire : ok=300, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  17%|██████▏                              | 311/1870 [44:52<2:41:07,  6.20s/article]

Sauvegarde intermédiaire : ok=310, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  17%|██████▎                              | 321/1870 [45:57<2:52:40,  6.69s/article]

Sauvegarde intermédiaire : ok=320, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  18%|██████▌                              | 331/1870 [47:49<4:31:49, 10.60s/article]

Sauvegarde intermédiaire : ok=330, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  18%|██████▋                              | 341/1870 [49:01<2:52:28,  6.77s/article]

Sauvegarde intermédiaire : ok=340, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  19%|██████▉                              | 351/1870 [50:06<2:29:39,  5.91s/article]

Sauvegarde intermédiaire : ok=350, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  19%|███████▏                             | 361/1870 [51:54<2:51:50,  6.83s/article]

Sauvegarde intermédiaire : ok=360, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  20%|███████▎                             | 371/1870 [56:03<3:48:15,  9.14s/article]

Sauvegarde intermédiaire : ok=370, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  20%|███████▌                             | 381/1870 [57:48<3:57:07,  9.56s/article]

Sauvegarde intermédiaire : ok=380, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  21%|███████▋                             | 391/1870 [58:59<3:07:30,  7.61s/article]

Sauvegarde intermédiaire : ok=390, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  21%|███████▌                           | 401/1870 [1:00:04<2:32:56,  6.25s/article]

Sauvegarde intermédiaire : ok=400, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  22%|███████▋                           | 411/1870 [1:01:35<2:57:35,  7.30s/article]

Sauvegarde intermédiaire : ok=410, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  23%|███████▉                           | 421/1870 [1:02:41<2:37:13,  6.51s/article]

Sauvegarde intermédiaire : ok=420, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  23%|████████                           | 431/1870 [1:04:20<3:31:40,  8.83s/article]

Sauvegarde intermédiaire : ok=430, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  24%|████████▎                          | 441/1870 [1:05:23<2:27:32,  6.19s/article]

Sauvegarde intermédiaire : ok=440, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  24%|████████▍                          | 451/1870 [1:06:27<2:36:48,  6.63s/article]

Sauvegarde intermédiaire : ok=450, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  25%|████████▋                          | 461/1870 [1:08:17<2:44:52,  7.02s/article]

Sauvegarde intermédiaire : ok=460, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  25%|████████▊                          | 471/1870 [1:09:32<2:39:56,  6.86s/article]

Sauvegarde intermédiaire : ok=470, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  26%|█████████                          | 481/1870 [1:11:14<3:35:18,  9.30s/article]

Sauvegarde intermédiaire : ok=480, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  26%|█████████▏                         | 491/1870 [1:13:59<2:47:43,  7.30s/article]

Sauvegarde intermédiaire : ok=490, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  27%|█████████▍                         | 501/1870 [1:15:08<2:35:52,  6.83s/article]

Sauvegarde intermédiaire : ok=500, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  27%|█████████▌                         | 511/1870 [1:16:36<2:26:51,  6.48s/article]

Sauvegarde intermédiaire : ok=510, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  28%|█████████▊                         | 521/1870 [1:17:43<2:29:38,  6.66s/article]

Sauvegarde intermédiaire : ok=520, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  28%|█████████▉                         | 531/1870 [1:19:17<3:22:15,  9.06s/article]

Sauvegarde intermédiaire : ok=530, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  29%|██████████▏                        | 541/1870 [1:20:25<2:35:52,  7.04s/article]

Sauvegarde intermédiaire : ok=540, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  29%|██████████▎                        | 551/1870 [1:21:33<2:11:35,  5.99s/article]

Sauvegarde intermédiaire : ok=550, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  30%|██████████▌                        | 561/1870 [1:23:21<2:38:33,  7.27s/article]

Sauvegarde intermédiaire : ok=560, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  31%|██████████▋                        | 571/1870 [1:24:30<2:28:49,  6.87s/article]

Sauvegarde intermédiaire : ok=570, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  31%|██████████▊                        | 581/1870 [1:26:13<3:13:15,  9.00s/article]

Sauvegarde intermédiaire : ok=580, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  32%|███████████                        | 591/1870 [1:27:24<2:36:57,  7.36s/article]

Sauvegarde intermédiaire : ok=590, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  32%|███████████▏                       | 601/1870 [1:28:29<2:23:28,  6.78s/article]

Sauvegarde intermédiaire : ok=600, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  33%|███████████▍                       | 611/1870 [1:32:51<3:14:37,  9.28s/article]

Sauvegarde intermédiaire : ok=610, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  33%|███████████▌                       | 621/1870 [1:33:58<2:22:35,  6.85s/article]

Sauvegarde intermédiaire : ok=620, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  34%|███████████▊                       | 631/1870 [1:35:44<3:22:01,  9.78s/article]

Sauvegarde intermédiaire : ok=630, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  34%|███████████▉                       | 641/1870 [1:36:50<2:21:32,  6.91s/article]

Sauvegarde intermédiaire : ok=640, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  35%|████████████▏                      | 651/1870 [1:37:54<2:11:07,  6.45s/article]

Sauvegarde intermédiaire : ok=650, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  35%|████████████▎                      | 661/1870 [1:40:54<4:48:42, 14.33s/article]

Sauvegarde intermédiaire : ok=660, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  36%|████████████▌                      | 671/1870 [1:42:00<2:25:48,  7.30s/article]

Sauvegarde intermédiaire : ok=670, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  36%|████████████▋                      | 681/1870 [1:43:35<2:54:31,  8.81s/article]

Sauvegarde intermédiaire : ok=680, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  37%|████████████▉                      | 691/1870 [1:44:35<1:57:30,  5.98s/article]

Sauvegarde intermédiaire : ok=690, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  37%|█████████████                      | 701/1870 [1:45:47<2:18:18,  7.10s/article]

Sauvegarde intermédiaire : ok=700, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  38%|█████████████▎                     | 711/1870 [1:47:32<2:19:07,  7.20s/article]

Sauvegarde intermédiaire : ok=710, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  39%|█████████████▍                     | 721/1870 [1:48:40<2:06:03,  6.58s/article]

Sauvegarde intermédiaire : ok=720, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  39%|█████████████▋                     | 731/1870 [1:51:49<3:04:44,  9.73s/article]

Sauvegarde intermédiaire : ok=730, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  40%|█████████████▊                     | 741/1870 [1:52:53<2:16:13,  7.24s/article]

Sauvegarde intermédiaire : ok=740, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  40%|██████████████                     | 751/1870 [1:54:01<1:59:35,  6.41s/article]

Sauvegarde intermédiaire : ok=750, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  41%|██████████████▏                    | 761/1870 [1:55:27<2:15:43,  7.34s/article]

Sauvegarde intermédiaire : ok=760, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  41%|██████████████▍                    | 771/1870 [1:56:32<1:57:38,  6.42s/article]

Sauvegarde intermédiaire : ok=770, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  42%|██████████████▌                    | 781/1870 [1:57:58<2:24:27,  7.96s/article]

Sauvegarde intermédiaire : ok=780, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  42%|██████████████▊                    | 791/1870 [1:59:06<2:08:34,  7.15s/article]

Sauvegarde intermédiaire : ok=790, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  43%|██████████████▉                    | 801/1870 [2:00:10<1:48:26,  6.09s/article]

Sauvegarde intermédiaire : ok=800, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  43%|███████████████▏                   | 811/1870 [2:01:46<2:07:05,  7.20s/article]

Sauvegarde intermédiaire : ok=810, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  44%|███████████████▎                   | 821/1870 [2:02:54<1:55:20,  6.60s/article]

Sauvegarde intermédiaire : ok=820, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  44%|███████████████▌                   | 831/1870 [2:04:45<2:54:50, 10.10s/article]

Sauvegarde intermédiaire : ok=830, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  45%|███████████████▋                   | 841/1870 [2:05:54<1:55:07,  6.71s/article]

Sauvegarde intermédiaire : ok=840, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  46%|███████████████▉                   | 851/1870 [2:09:39<2:31:29,  8.92s/article]

Sauvegarde intermédiaire : ok=850, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  46%|████████████████                   | 861/1870 [2:11:23<2:07:00,  7.55s/article]

Sauvegarde intermédiaire : ok=860, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  47%|████████████████▎                  | 871/1870 [2:12:22<1:39:39,  5.99s/article]

Sauvegarde intermédiaire : ok=870, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  47%|████████████████▍                  | 881/1870 [2:14:05<2:26:14,  8.87s/article]

Sauvegarde intermédiaire : ok=880, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  48%|████████████████▋                  | 891/1870 [2:15:11<1:55:47,  7.10s/article]

Sauvegarde intermédiaire : ok=890, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  48%|████████████████▊                  | 901/1870 [2:16:18<1:50:55,  6.87s/article]

Sauvegarde intermédiaire : ok=900, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  49%|█████████████████                  | 911/1870 [2:17:44<1:41:56,  6.38s/article]

Sauvegarde intermédiaire : ok=910, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  49%|█████████████████▏                 | 921/1870 [2:18:54<1:45:02,  6.64s/article]

Sauvegarde intermédiaire : ok=920, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  50%|█████████████████▍                 | 931/1870 [2:20:20<2:13:43,  8.54s/article]

Sauvegarde intermédiaire : ok=930, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  50%|█████████████████▌                 | 941/1870 [2:21:25<1:42:59,  6.65s/article]

Sauvegarde intermédiaire : ok=940, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  51%|█████████████████▊                 | 951/1870 [2:22:33<1:40:29,  6.56s/article]

Sauvegarde intermédiaire : ok=950, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  51%|█████████████████▉                 | 961/1870 [2:24:09<2:02:23,  8.08s/article]

Sauvegarde intermédiaire : ok=960, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  52%|██████████████████▏                | 971/1870 [2:27:15<2:16:34,  9.11s/article]

Sauvegarde intermédiaire : ok=970, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  52%|██████████████████▎                | 981/1870 [2:28:37<1:56:30,  7.86s/article]

Sauvegarde intermédiaire : ok=980, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  53%|██████████████████▌                | 991/1870 [2:29:49<1:48:42,  7.42s/article]

Sauvegarde intermédiaire : ok=990, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  54%|██████████████████▏               | 1001/1870 [2:30:58<1:43:47,  7.17s/article]

Sauvegarde intermédiaire : ok=1000, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  54%|██████████████████▍               | 1011/1870 [2:32:42<1:54:11,  7.98s/article]

Sauvegarde intermédiaire : ok=1010, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  55%|██████████████████▌               | 1021/1870 [2:33:49<1:41:23,  7.17s/article]

Sauvegarde intermédiaire : ok=1020, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  55%|██████████████████▋               | 1031/1870 [2:35:37<2:09:30,  9.26s/article]

Sauvegarde intermédiaire : ok=1030, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  56%|██████████████████▉               | 1041/1870 [2:36:43<1:34:34,  6.84s/article]

Sauvegarde intermédiaire : ok=1040, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  56%|███████████████████               | 1051/1870 [2:37:52<1:32:15,  6.76s/article]

Sauvegarde intermédiaire : ok=1050, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  57%|███████████████████▎              | 1061/1870 [2:39:28<1:27:43,  6.51s/article]

Sauvegarde intermédiaire : ok=1060, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  57%|███████████████████▍              | 1071/1870 [2:40:38<1:26:42,  6.51s/article]

Sauvegarde intermédiaire : ok=1070, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  58%|███████████████████▋              | 1081/1870 [2:42:24<2:05:22,  9.53s/article]

Sauvegarde intermédiaire : ok=1080, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  58%|███████████████████▊              | 1091/1870 [2:45:20<1:36:12,  7.41s/article]

Sauvegarde intermédiaire : ok=1090, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  59%|████████████████████              | 1101/1870 [2:46:24<1:23:39,  6.53s/article]

Sauvegarde intermédiaire : ok=1100, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  59%|████████████████████▏             | 1111/1870 [2:48:14<1:29:34,  7.08s/article]

Sauvegarde intermédiaire : ok=1110, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  60%|████████████████████▍             | 1121/1870 [2:49:17<1:18:24,  6.28s/article]

Sauvegarde intermédiaire : ok=1120, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  60%|████████████████████▌             | 1131/1870 [2:51:04<1:56:31,  9.46s/article]

Sauvegarde intermédiaire : ok=1130, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  61%|████████████████████▋             | 1141/1870 [2:52:03<1:17:18,  6.36s/article]

Sauvegarde intermédiaire : ok=1140, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  62%|████████████████████▉             | 1151/1870 [2:53:02<1:10:33,  5.89s/article]

Sauvegarde intermédiaire : ok=1150, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  62%|█████████████████████             | 1161/1870 [2:54:52<1:27:54,  7.44s/article]

Sauvegarde intermédiaire : ok=1160, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  63%|█████████████████████▎            | 1171/1870 [2:56:01<1:23:47,  7.19s/article]

Sauvegarde intermédiaire : ok=1170, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  63%|█████████████████████▍            | 1181/1870 [2:57:53<2:02:45, 10.69s/article]

Sauvegarde intermédiaire : ok=1180, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  64%|█████████████████████▋            | 1191/1870 [2:59:01<1:20:24,  7.11s/article]

Sauvegarde intermédiaire : ok=1190, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  64%|█████████████████████▊            | 1201/1870 [3:00:07<1:11:14,  6.39s/article]

Sauvegarde intermédiaire : ok=1200, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  65%|██████████████████████            | 1211/1870 [3:03:41<1:29:58,  8.19s/article]

Sauvegarde intermédiaire : ok=1210, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  65%|██████████████████████▏           | 1221/1870 [3:04:53<1:16:12,  7.04s/article]

Sauvegarde intermédiaire : ok=1220, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  66%|██████████████████████▍           | 1231/1870 [3:06:45<1:47:21, 10.08s/article]

Sauvegarde intermédiaire : ok=1230, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  66%|██████████████████████▌           | 1241/1870 [3:07:57<1:12:49,  6.95s/article]

Sauvegarde intermédiaire : ok=1240, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  67%|██████████████████████▋           | 1251/1870 [3:09:10<1:15:42,  7.34s/article]

Sauvegarde intermédiaire : ok=1250, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  67%|██████████████████████▉           | 1261/1870 [3:10:38<1:16:29,  7.54s/article]

Sauvegarde intermédiaire : ok=1260, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  68%|███████████████████████           | 1271/1870 [3:11:49<1:12:28,  7.26s/article]

Sauvegarde intermédiaire : ok=1270, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  69%|███████████████████████▎          | 1281/1870 [3:13:09<1:19:33,  8.10s/article]

Sauvegarde intermédiaire : ok=1280, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  69%|███████████████████████▍          | 1291/1870 [3:14:13<1:06:49,  6.93s/article]

Sauvegarde intermédiaire : ok=1290, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  70%|███████████████████████▋          | 1301/1870 [3:15:18<1:05:10,  6.87s/article]

Sauvegarde intermédiaire : ok=1300, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  70%|███████████████████████▊          | 1311/1870 [3:16:43<1:07:29,  7.24s/article]

Sauvegarde intermédiaire : ok=1310, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  71%|█████████████████████████▍          | 1321/1870 [3:17:50<58:08,  6.35s/article]

Sauvegarde intermédiaire : ok=1320, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  71%|████████████████████████▏         | 1331/1870 [3:21:41<1:45:12, 11.71s/article]

Sauvegarde intermédiaire : ok=1330, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  72%|█████████████████████████▊          | 1341/1870 [3:22:41<53:18,  6.05s/article]

Sauvegarde intermédiaire : ok=1340, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  72%|██████████████████████████          | 1351/1870 [3:23:52<59:59,  6.94s/article]

Sauvegarde intermédiaire : ok=1350, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  73%|██████████████████████████▏         | 1361/1870 [3:25:29<59:39,  7.03s/article]

Sauvegarde intermédiaire : ok=1360, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  73%|██████████████████████████▍         | 1371/1870 [3:26:40<53:03,  6.38s/article]

Sauvegarde intermédiaire : ok=1370, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  74%|█████████████████████████         | 1381/1870 [3:28:16<1:11:26,  8.77s/article]

Sauvegarde intermédiaire : ok=1380, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  74%|██████████████████████████▊         | 1391/1870 [3:29:18<47:30,  5.95s/article]

Sauvegarde intermédiaire : ok=1390, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  75%|██████████████████████████▉         | 1401/1870 [3:30:25<49:31,  6.34s/article]

Sauvegarde intermédiaire : ok=1400, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  75%|███████████████████████████▏        | 1411/1870 [3:32:05<54:07,  7.08s/article]

Sauvegarde intermédiaire : ok=1410, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  76%|███████████████████████████▎        | 1421/1870 [3:33:11<51:11,  6.84s/article]

Sauvegarde intermédiaire : ok=1420, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  77%|██████████████████████████        | 1431/1870 [3:35:03<1:13:09, 10.00s/article]

Sauvegarde intermédiaire : ok=1430, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  77%|███████████████████████████▋        | 1441/1870 [3:36:06<45:15,  6.33s/article]

Sauvegarde intermédiaire : ok=1440, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  78%|██████████████████████████▍       | 1451/1870 [3:39:37<1:04:54,  9.30s/article]

Sauvegarde intermédiaire : ok=1450, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  78%|████████████████████████████▏       | 1461/1870 [3:41:17<46:16,  6.79s/article]

Sauvegarde intermédiaire : ok=1460, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  79%|████████████████████████████▎       | 1471/1870 [3:42:16<38:07,  5.73s/article]

Sauvegarde intermédiaire : ok=1470, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  79%|████████████████████████████▌       | 1481/1870 [3:43:41<48:37,  7.50s/article]

Sauvegarde intermédiaire : ok=1480, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  80%|████████████████████████████▋       | 1491/1870 [3:44:51<44:47,  7.09s/article]

Sauvegarde intermédiaire : ok=1490, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  80%|████████████████████████████▉       | 1501/1870 [3:45:58<39:24,  6.41s/article]

Sauvegarde intermédiaire : ok=1500, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  81%|█████████████████████████████       | 1511/1870 [3:47:35<41:25,  6.92s/article]

Sauvegarde intermédiaire : ok=1510, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  81%|█████████████████████████████▎      | 1521/1870 [3:48:38<37:40,  6.48s/article]

Sauvegarde intermédiaire : ok=1520, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  82%|█████████████████████████████▍      | 1531/1870 [3:50:06<42:50,  7.58s/article]

Sauvegarde intermédiaire : ok=1530, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  82%|█████████████████████████████▋      | 1541/1870 [3:51:17<38:36,  7.04s/article]

Sauvegarde intermédiaire : ok=1540, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  83%|█████████████████████████████▊      | 1551/1870 [3:52:24<36:52,  6.94s/article]

Sauvegarde intermédiaire : ok=1550, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  83%|██████████████████████████████      | 1561/1870 [3:53:47<35:38,  6.92s/article]

Sauvegarde intermédiaire : ok=1560, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  84%|██████████████████████████████▏     | 1571/1870 [3:56:38<38:12,  7.67s/article]

Sauvegarde intermédiaire : ok=1570, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  85%|██████████████████████████████▍     | 1581/1870 [3:58:29<47:49,  9.93s/article]

Sauvegarde intermédiaire : ok=1580, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  85%|██████████████████████████████▋     | 1591/1870 [3:59:33<30:16,  6.51s/article]

Sauvegarde intermédiaire : ok=1590, échecs=0, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  86%|██████████████████████████████▊     | 1601/1870 [4:01:04<45:49, 10.22s/article]

Sauvegarde intermédiaire : ok=1599, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  86%|███████████████████████████████     | 1611/1870 [4:02:41<28:38,  6.63s/article]

Sauvegarde intermédiaire : ok=1609, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  87%|███████████████████████████████▏    | 1621/1870 [4:03:51<28:17,  6.82s/article]

Sauvegarde intermédiaire : ok=1619, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  87%|███████████████████████████████▍    | 1631/1870 [4:05:21<33:53,  8.51s/article]

Sauvegarde intermédiaire : ok=1629, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  88%|███████████████████████████████▌    | 1641/1870 [4:06:27<22:29,  5.89s/article]

Sauvegarde intermédiaire : ok=1639, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  88%|███████████████████████████████▊    | 1651/1870 [4:07:39<27:57,  7.66s/article]

Sauvegarde intermédiaire : ok=1649, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  89%|███████████████████████████████▉    | 1661/1870 [4:09:16<23:25,  6.73s/article]

Sauvegarde intermédiaire : ok=1659, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  89%|████████████████████████████████▏   | 1671/1870 [4:10:27<24:18,  7.33s/article]

Sauvegarde intermédiaire : ok=1669, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  90%|████████████████████████████████▎   | 1681/1870 [4:12:16<32:48, 10.42s/article]

Sauvegarde intermédiaire : ok=1679, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  90%|████████████████████████████████▌   | 1691/1870 [4:15:45<27:28,  9.21s/article]

Sauvegarde intermédiaire : ok=1689, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  91%|████████████████████████████████▋   | 1701/1870 [4:16:53<17:26,  6.19s/article]

Sauvegarde intermédiaire : ok=1699, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  91%|████████████████████████████████▉   | 1711/1870 [4:18:12<16:43,  6.31s/article]

Sauvegarde intermédiaire : ok=1709, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  92%|█████████████████████████████████▏  | 1721/1870 [4:19:17<16:05,  6.48s/article]

Sauvegarde intermédiaire : ok=1719, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  93%|█████████████████████████████████▎  | 1731/1870 [4:20:59<21:45,  9.39s/article]

Sauvegarde intermédiaire : ok=1729, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  93%|█████████████████████████████████▌  | 1741/1870 [4:22:04<13:30,  6.28s/article]

Sauvegarde intermédiaire : ok=1739, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  94%|█████████████████████████████████▋  | 1751/1870 [4:23:13<13:30,  6.81s/article]

Sauvegarde intermédiaire : ok=1749, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  94%|█████████████████████████████████▉  | 1761/1870 [4:25:01<13:01,  7.17s/article]

Sauvegarde intermédiaire : ok=1759, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  95%|██████████████████████████████████  | 1771/1870 [4:26:14<12:00,  7.28s/article]

Sauvegarde intermédiaire : ok=1769, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  95%|██████████████████████████████████▎ | 1781/1870 [4:28:12<15:15, 10.28s/article]

Sauvegarde intermédiaire : ok=1779, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  96%|██████████████████████████████████▍ | 1791/1870 [4:29:19<08:19,  6.33s/article]

Sauvegarde intermédiaire : ok=1789, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  96%|██████████████████████████████████▋ | 1801/1870 [4:30:24<06:30,  5.66s/article]

Sauvegarde intermédiaire : ok=1799, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  97%|██████████████████████████████████▊ | 1811/1870 [4:35:04<08:57,  9.11s/article]

Sauvegarde intermédiaire : ok=1809, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  97%|███████████████████████████████████ | 1821/1870 [4:36:18<05:45,  7.06s/article]

Sauvegarde intermédiaire : ok=1819, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  98%|███████████████████████████████████▏| 1831/1870 [4:37:50<05:31,  8.50s/article]

Sauvegarde intermédiaire : ok=1829, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  98%|███████████████████████████████████▍| 1841/1870 [4:38:58<03:08,  6.51s/article]

Sauvegarde intermédiaire : ok=1839, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles:  99%|███████████████████████████████████▋| 1851/1870 [4:40:03<01:57,  6.19s/article]

Sauvegarde intermédiaire : ok=1849, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles: 100%|███████████████████████████████████▊| 1861/1870 [4:41:47<01:07,  7.48s/article]

Sauvegarde intermédiaire : ok=1859, échecs=1, sautés=1 -> tass_clean/tass_clean_with_text.json

Articles: 100%|████████████████████████████████████| 1870/1870 [4:42:48<00:00,  9.07s/article]

=== TERMINÉ ===
Réussites : 1868
Échecs    : 1
Sautés    : 1
Fichier   : tass_clean/tass_clean_with_text.json

## 10. Chargement du corpus enrichi

Une fois le scraping terminé, cette cellule recharge le fichier contenant les textes intégraux et le transforme en `DataFrame`. Le corpus final contient désormais les métadonnées initiales ainsi que le texte complet de l’article et les hashtags éventuellement récupérés.

In [16]:

input_path = "tass_clean_with_text.json"

with open(input_path, "r", encoding="utf-8") as f:
    data = json.load(f)

rows = []
for obj in data:
    title = obj.get("title")
    published_dt = obj.get("published_dt")
    url = obj.get("url")

    if title and published_dt:
        rows.append({
            "title": title,
            "published_dt": published_dt,
            "url": url, 
            "text": obj.get("text", ""),
            "hashtags": obj.get("hashtags", [])
        })

df = pd.DataFrame(rows)

df

,title,published_dt,url,text,hashtags
0,"Волонтеры развернули штаб ""Мы вместе"" для помо...",2022-02-18T22:21:32,https://tass.ru/obschestvo/13763103,"МОСКВА, 19 февраля. /ТАСС/. Волонтеры Общеросс...",[]
1,"Волонтер рассказал о помощи жителям ДНР, котор...",2022-02-18T22:09:51,https://tass.ru/obschestvo/13762975,"РОСТОВ-НА-ДОНУ, 19 февраля. /ТАСС/. Жителей ДН...","[Кризис на Украине, Россия, Ростовская область]"
2,Роспотребнадзор уделит особое внимание организ...,2022-02-18T20:56:09,https://tass.ru/obschestvo/13762457,"МОСКВА, 19 февраля. /ТАСС/. Руководитель Роспо...","[Кризис на Украине, Попова, Анна Юрьевна, Росс..."
3,Из Луганска в Россию отправился первый автобус...,2022-02-18T20:53:55,https://tass.ru/obschestvo/13762389,"ЛУГАНСК, 18 февраля. /ТАСС/. Первый автобус с ...","[Кризис на Украине, Россия, Украина]"
4,Источник: для эвакуированных из ДНР и ЛНР разв...,2022-02-18T20:53:50,https://tass.ru/obschestvo/13762407,"МАТВЕЕВ КУРГАН /Ростовская область/, 18 феврал...","[Кризис на Украине, Россия, Ростовская область]"
...,...,...,...,...,...
1865,"""10 километров мимо неразорвавшихся мин"".",2022-04-13 05:15:00,https://tass.ru/v-strane/14340553,Очередной автобус подъезжает к пункту пропуска...,"[Владимирская область, Военная операция на Укр..."
1866,В ООН дали высокую оценку действиям России по ...,2022-06-24 11:41:00,https://tass.ru/obschestvo/15024555,"МОСКВА, 24 июня. /ТАСС/. Россия достойно и на ...","[Военная операция на Украине, Россия, Украина]"
1867,Украинские беженцы потянулись домой:,2022-07-21 13:51:00,https://tass.ru/opinions/15276009,"Потоки украинцев, приезжающих в Европу и уезжа...","[Военная операция на Украине, Кризис на Украин..."
1868,"В страны Европы с 24 февраля прибыли более 7,6...",2022-10-05 19:26:00,https://tass.ru/obschestvo/15967821,"ЖЕНЕВА, 5 октября. /ТАСС/. Управление верховно...",[Украина]
1869,Российское гражданство с 2019 года получили бо...,2023-02-02 07:56:00,https://tass.ru/obschestvo/16943909,"МОСКВА, 2 февраля. /ТАСС/. Свыше 1,4 млн гражд...","[Россия, Украина]"

## 11. Vérification des textes manquants

Cette dernière vérification compte le nombre d’articles pour lesquels le champ `text` est vide ou absent. Elle permet d’évaluer la qualité du scraping et de repérer les pages qui devront éventuellement être reprises ou contrôlées manuellement.

In [17]:
# nombre de lignes sans texte
no_text = df["text"].apply(lambda x: not isinstance(x, str) or len(x.strip()) == 0)
num_no_text = no_text.sum()
print("Nombre de lignes sans texte:", num_no_text)

Nombre de lignes sans texte: 0